2021-07-12 15:53:15,256-conftest-INFO-清除成功
2021-07-12 15:53:15,257-case.test_api-INFO-正常账号密码登录开始测试
2021-07-12 15:53:15,717-case.test_api-INFO-正常账号密码登录接口响应时间为:0.456351秒
2021-07-12 15:53:15,717-case.test_api-INFO-正常账号密码登录用例返回结果为:{'code': 0, 'data': {'token': 'K2dTni55E7z2DxxU2JpZFjEpiIAr3ahsWDBz', 'registered': True, 'inviteBy': '564945', 'kyToken': 'yXjc4WLb0cB351tlcEV1nPmBnTpJ55Ge9Vrv', 'uid': 5, 'newUser': False}}
2021-07-12 15:53:15,719-case.test_api-INFO-正常账号密码登录测试完成
2021-07-12 15:53:15,720-case.test_api-INFO-错误密码登录开始测试
2021-07-12 15:53:15,732-case.test_api-INFO-错误密码登录接口响应时间为:0.01026秒
2021-07-12 15:53:15,733-case.test_api-INFO-错误密码登录用例返回结果为:{'code': 1, 'error': '密码不正确，请重新输入'}
2021-07-12 15:53:15,733-case.test_api-INFO-错误密码登录测试完成
2021-07-12 15:53:15,734-case.test_api-INFO-未加密密码登录开始测试
2021-07-12 15:53:15,743-case.test_api-INFO-未加密密码登录接口响应时间为:0.007331秒
2021-07-12 15:53:15,743-case.test_api-INFO-未加密密码登录用例返回结果为:{'code': 1, 'error': '密码不正确，请重新输入'}
2021-07-12 15:53:15,744-case.test_api-INFO-未加密密码登录测试完成
2021-07-12 15:53:15,746-case.test_api-INFO-点亮列表开始测试
2021-07-12 15:53:15,749-case.test_api-INFO-用例请求返回失败，HTTPConnectionPool(host='127.0.0.1', port=8888): Max retries exceeded with url: http://115.236.35.106:9000/api/n/lightup/by/adcode/list?longitude=120.159708&latitude=30.325324&page=82&size=10&adcode=330100 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
